---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.


Prudvik Seemakurthi: This line is from Prudvik

This was my first time connecting RStudio to GitHub, and the process was quite exciting. I received help from a team member and was able to work through some minor issues. However, I ran into a problem while pushing files due to a missing personal access token. I referred to the notes in Chapter 9, where I learned how to create a personal access token, and that helped me resolve the pull error successfully.


David Wang: This is a line from RStudio

12.1 Prerequisites

12.2 Make a repo on GitHub

12.3 Clone the test GitHub repository to your computer via RStudio

12.4 Make local changes, save, commit

12.5 Push your local changes online to GitHub

12.6 Confirm the local change propagated to the GitHub remote

Did not delete repo for 12.7

David Notes from Lab: I have had previous experience with git, however I am not used to using RStudio; so I cloned it with the terminal rather than using the RStudio GUI at first, which caused me a bit of confusion. Then I realized my issue when I couldn't find the Git tab, so I instead cloned the repository with help of my team members through RStudio instead. After I could access the Git tab, I made the RStudio line commit and was able to push it to the repository.


Kelly Arriaza: THis is a line from RStudio

Kelly notes from Lab: I ran into some issues because I did not have previous experience with git. I had to restart a few times to be sure that I was properly connecting git and RStudio. Once everything was properly connected and I had help from my team members, it was more simple than I had expected to use the commit and push commands.
